### ISSUE TITLE
TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by lin-xin** [hchstera/vue-charts#11]
When I use the  '< chartjs - pie > < / chartjs - pie >',the console will print out the error message "TypeError: Cannot read property 'concat' of undefined".

But I use other components are correct !

**Comment by g9308370** [comment]
Any sample code with the error message  "TypeError: Cannot read property 'concat' of undefined".  ?
I tried to render pie-chart by using version 1.2.7. it worked well.

什麼情況下發生這個錯誤的? 我試著做圓餅圖看似正常
code pen參考看看。

[Code Pen](http://codepen.io/g9308370/pen/ZLdMwW)

**Comment by lin-xin** [comment]
我使用的chart.js版本是”2.5.0“的就会发生这个错误，使用”2.3.0“的就没错了。
