### ISSUE TITLE
Mouse over on Multiline chart

### ISSUE THREAD

**Issue by nezaboravi** [hchstera/vue-charts#15]
Mouse over on Multiline chart reflects all point in that vertical to show up.
GO to demo, and find 2 lines chart, mouse over one point and you will see other point above acts like mouse is over it as well

**Comment by g9308370** [comment]
yap. Multi chart reflects all  **vertical** point, and trigger the hover event.

In [Chart.js Document page](http://www.chartjs.org/)
You can see the **Mixed chart types**. in that vertical to show up whern mouse over on chart.
