### ISSUE TITLE
Pie and doughnut graph does not render

### ISSUE THREAD

**Issue by jmarroyave** [hchstera/vue-charts#16]
http://vue-charts.hchspersonal.tk/pie
http://vue-charts.hchspersonal.tk/doughnut

It's related to the size defaults

**Comment by g9308370** [comment]
maybe you loaded old version?
You can try **ctrl+F5** if the chart doesn't render in demo page.  

and
(By using Chart.js 2.5.0) The pie&dougnut chart default size (without setting **:width :height**) bigger than version 2.3.0
I have no time to check or improve that.

RWD looks work well btw. uh.. just a little big.

**Comment by jmarroyave** [comment]
got it, thanks
