### ISSUE TITLE
How to use in vue components of webpack?

### ISSUE THREAD

**Issue by AaronW-BE** [hchstera/vue-charts#19]
I will use vue-charts in webpack project, but i still dont know how to setup in main.js. Need i edit index.html file ?

**Comment by fyyyyy** [comment]
This works

Dont do  `import VueChart from 'hchs-vue-charts`, use the global window.VueChart instead to initialize with Vue.

```
import Vue from 'vue';
import 'chart.js';
import 'hchs-vue-charts';

Vue.use(window.VueCharts);
```

**Comment by jofftiquez** [comment]
Still it would be better to create a build for `commonjs-2`
