### ISSUE TITLE
How to set horizontal bar begin at zero?

### ISSUE THREAD

**Issue by phamvanthanh** [hchstera/vue-charts#29]
Hi @yeknava, @joecampo 
When using multiple horizontal bars, the bars do not start at  0 bar end of previous bars. please see image
No problem if vertical bars.
How to fix this?
![oie_co98hz4akh26](https://user-images.githubusercontent.com/24784468/27583928-48f42d6e-5b60-11e7-83f5-c48db98c8041.png)

**Comment by yeknava** [comment]
hi @phamvanthanh,
im not sure but checkout [this code](https://github.com/hchstera/vue-charts/blob/master/src/components/chartjs-horizontal-bar.vue) and remove stacked options from horizontalBar

**Comment by phamvanthanh** [comment]
Many thanks @yeknava 
It works.

**Comment by yeknava** [comment]
@phamvanthanh welcome, if there is no bug tell me to remove it from package code or you do it yourself with a pull request ;)
