### ISSUE TITLE
Doughnut Progress Chart

### ISSUE THREAD

**Issue by MaksimSkomorokh** [hchstera/vue-charts#4]
Is possible to create progress chart [like this](http://codepen.io/Shyam-Chen/pen/bBWKKy) ?

**Comment by g9308370** [comment]
No plan to create a progress chart component.

This project dependencies on [chart.js](http://www.chartjs.org/).
and chart.js doesn't support progress chart.

You can try [vue-spinner](https://github.com/greyby/vue-spinner), or [progressbar.js](https://kimmobrunfeldt.github.io/progressbar.js/)
