### ISSUE TITLE
Can't dynamically update the chart by an event.

### ISSUE THREAD

**Issue by davepoon** [hchstera/vue-charts#5]
I am using the script tag way to load vue-charts. 
I have setup an event to click a button to update the chart labels and the datasets data which are binding to the stacked bar chart. :bind=true is on in the chartjs-bar, but the chart doesn't autoupdate when the value changed.

This is the jsfiddle code to replicate the issue,
https://jsfiddle.net/cqkf3hyp/3/

Thank you for making this wonderful vue-charts ;)

**Comment by g9308370** [comment]
Hi,
the autoupdate bug has been fix.

You can try this. 
[Code Pen Demo With Ver.1.2.5](http://codepen.io/g9308370/pen/qqYJdm)

thanks for ur report. and could I add the autoupdate  demo in README file?
