### ISSUE TITLE
is it possible to get click event on chart

### ISSUE THREAD

**Issue by zhihuiFan** [hchstera/vue-charts#8]
for example,  I click one part of the pie.  I want to handle this action by knowing the "label" and "value" for that piece. 

is it possible for now?

thanks

**Comment by si262001** [comment]
<div id="appbar">
<chartjs-bar :option="myoption" :data="num" :labels="labels" :bind="true" ></chartjs-bar>
</div>
<script>
Vue.use(VueCharts);
const appbar = new Vue({
    el: '#appbar',
    data:{
        "num":[1,2,3],
        "labels":["a","b","c"]
        myoption:{
            onClick:function(evt){
                var activeElement = this.tooltipActive[0]
                if(typeof activeElement=="undefined"){return}
                alert(activeElement._model.label)
            }
        }
    },
});
<script>

**Comment by zhihuiFan** [comment]
Thanks, that's what I wanted.
